# Generated by Django 6.0.7 on 2026-07-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0003_examen_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionmodel',
            name='entorno_practica',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seccionmodel',
            name='guia_paso_a_paso',
            field=models.TextField(blank=True, default=''),
        ),
    ]
