# Generated by Django 6.0.7 on 2026-07-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0004_seccionmodel_entorno_practica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccionmodel',
            name='imagen_practica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
