# Generated by Django 6.0.7 on 2026-07-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0005_seccionmodel_imagen_practica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccionmodel',
            name='guia_paso_a_paso',
        ),
        migrations.AddField(
            model_name='laboratoriomodel',
            name='resumen_cierre',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='seccionmodel',
            name='duracion_estimada_minutos',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='seccionmodel',
            name='objetivos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='seccionmodel',
            name='pasos_guia',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
