# Generated by Django 6.0.7 on 2026-07-30 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0006_remove_seccionmodel_guia_paso_a_paso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoriomodel',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratoriomodel',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('publicado', 'Publicado')], default='borrador', max_length=20),
        ),
        migrations.CreateModel(
            name='DockerfileSeccionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo_url', models.CharField(max_length=500)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tamano_kb', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dockerfile', to='laboratories.seccionmodel')),
            ],
            options={
                'db_table': 'laboratories_dockerfile_seccion',
            },
        ),
    ]
