# Generated by Django 6.0.7 on 2026-07-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0007_laboratoriomodel_motivo_rechazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoriomodel',
            name='visible_en_catalogo',
            field=models.BooleanField(default=False),
        ),
    ]
