# Generated by Django 6.0.7 on 2026-07-30 01:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntornoActivoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seccion_id', models.UUIDField()),
                ('progreso_id', models.UUIDField()),
                ('estudiante_id', models.UUIDField()),
                ('container_id', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('iniciando', 'Iniciando'), ('activo', 'Activo'), ('detenido', 'Detenido'), ('error', 'Error')], default='iniciando', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lab_environments_entornoactivo',
                'indexes': [models.Index(fields=['estado', 'ultima_actividad'], name='idx_entorno_estado_actividad'), models.Index(fields=['progreso_id', 'seccion_id'], name='idx_entorno_progreso_seccion')],
            },
        ),
    ]
