# Generated by Django 6.0.7 on 2026-07-15 04:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('instructor', 'Instructor'), ('administrador', 'Administrador')], default='estudiante', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users_user',
            },
        ),
        migrations.CreateModel(
            name='ProveedorAutenticacionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proveedor', models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('github', 'GitHub')], max_length=20)),
                ('proveedor_uid', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='users.usermodel')),
            ],
            options={
                'db_table': 'users_proveedorautenticacion',
                'constraints': [models.UniqueConstraint(fields=('user', 'proveedor'), name='uq_user_proveedor'), models.UniqueConstraint(fields=('proveedor', 'proveedor_uid'), name='uq_proveedor_uid')],
            },
        ),
    ]
