# Generated by Django 6.0.7 on 2026-07-30 19:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInstructorModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orcid', models.CharField(db_index=True, max_length=19)),
                ('nombre_declarado', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=30)),
                ('institucion', models.CharField(blank=True, max_length=200)),
                ('especialidades', models.CharField(blank=True, max_length=300)),
                ('motivacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=300, null=True)),
                ('resultado_verificacion', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_instructor', to='users.usermodel')),
            ],
            options={
                'db_table': 'users_solicitudinstructor',
            },
        ),
    ]
