import uuid
from typing import Protocol

from modules.gamification.domain.entities import (
    Cosmetico,
    CosmeticoDesbloqueado,
    Logro,
    LogroDesbloqueado,
    PerfilJugador,
    Titulo,
    TituloDesbloqueado,
    XpOtorgado,
)


class IPerfilJugadorRepository(Protocol):
    def get_by_estudiante(self, estudiante_id: uuid.UUID) -> PerfilJugador | None: ...

    def add(self, perfil: PerfilJugador) -> PerfilJugador: ...

    def update(self, perfil: PerfilJugador) -> PerfilJugador: ...


class IXpOtorgadoRepository(Protocol):
    def existe(self, estudiante_id: uuid.UUID, laboratorio_id: uuid.UUID) -> bool: ...

    def add(self, xp_otorgado: XpOtorgado) -> XpOtorgado: ...

    def contar_por_estudiante(self, estudiante_id: uuid.UUID) -> int: ...

    def find_laboratorio_ids_por_estudiante(self, estudiante_id: uuid.UUID) -> set[uuid.UUID]: ...


class ILogroRepository(Protocol):
    def find_todos(self) -> list[Logro]: ...

    def get_by_id(self, logro_id: uuid.UUID) -> Logro | None: ...

    def get_by_clave(self, clave: str) -> Logro | None: ...

    def add(self, logro: Logro) -> Logro: ...

    def find_por_tipo(self, tipo_criterio: str) -> list[Logro]: ...


class ILogroDesbloqueadoRepository(Protocol):
    def existe(self, estudiante_id: uuid.UUID, logro_id: uuid.UUID) -> bool: ...

    def add(self, desbloqueo: LogroDesbloqueado) -> LogroDesbloqueado: ...

    def find_por_estudiante(self, estudiante_id: uuid.UUID) -> list[LogroDesbloqueado]: ...


class ICosmeticoRepository(Protocol):
    def find_todos(self) -> list[Cosmetico]: ...

    def get_by_id(self, cosmetico_id: uuid.UUID) -> Cosmetico | None: ...

    def get_by_clave(self, clave: str) -> Cosmetico | None: ...

    def add(self, cosmetico: Cosmetico) -> Cosmetico: ...

    def find_por_logro(self, logro_id: uuid.UUID) -> list[Cosmetico]: ...


class ICosmeticoDesbloqueadoRepository(Protocol):
    def get_by_id(self, desbloqueo_id: uuid.UUID) -> CosmeticoDesbloqueado | None: ...

    def existe(self, estudiante_id: uuid.UUID, cosmetico_id: uuid.UUID) -> bool: ...

    def add(self, desbloqueo: CosmeticoDesbloqueado) -> CosmeticoDesbloqueado: ...

    def find_por_estudiante(self, estudiante_id: uuid.UUID) -> list[CosmeticoDesbloqueado]: ...

    def update(self, desbloqueo: CosmeticoDesbloqueado) -> CosmeticoDesbloqueado: ...


class ITituloRepository(Protocol):
    def find_todos(self) -> list[Titulo]: ...

    def get_by_id(self, titulo_id: uuid.UUID) -> Titulo | None: ...

    def get_by_clave(self, clave: str) -> Titulo | None: ...

    def add(self, titulo: Titulo) -> Titulo: ...

    def find_por_logro(self, logro_id: uuid.UUID) -> list[Titulo]: ...


class ITituloDesbloqueadoRepository(Protocol):
    def get_by_id(self, desbloqueo_id: uuid.UUID) -> TituloDesbloqueado | None: ...

    def existe(self, estudiante_id: uuid.UUID, titulo_id: uuid.UUID) -> bool: ...

    def add(self, desbloqueo: TituloDesbloqueado) -> TituloDesbloqueado: ...

    def find_por_estudiante(self, estudiante_id: uuid.UUID) -> list[TituloDesbloqueado]: ...

    def update(self, desbloqueo: TituloDesbloqueado) -> TituloDesbloqueado: ...
