# Generated by Django 6.0.7 on 2026-07-31 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogroModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('tipo_criterio', models.CharField(choices=[('primer_laboratorio', 'Primer laboratorio'), ('n_laboratorios', 'N laboratorios'), ('categoria_roadmap_completa', 'Categoría de roadmap completa')], max_length=30)),
                ('criterio_valor', models.CharField(blank=True, max_length=100, null=True)),
                ('rareza', models.CharField(choices=[('comun', 'Común'), ('poco_comun', 'Poco común'), ('raro', 'Raro'), ('epico', 'Épico'), ('legendario', 'Legendario'), ('mitico', 'Mítico')], max_length=20)),
            ],
            options={
                'db_table': 'gamification_logro',
            },
        ),
        migrations.CreateModel(
            name='PerfilJugadorModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estudiante_id', models.UUIDField(unique=True)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gamification_perfil_jugador',
            },
        ),
        migrations.CreateModel(
            name='CosmeticoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('hoodie', 'Hoodie'), ('gafas', 'Gafas'), ('mascara', 'Máscara'), ('aura', 'Aura'), ('insignia', 'Insignia'), ('mochila', 'Mochila'), ('guantes', 'Guantes'), ('zapatos', 'Zapatos'), ('gorra', 'Gorra'), ('audifonos', 'Audífonos')], max_length=20)),
                ('rareza', models.CharField(choices=[('comun', 'Común'), ('poco_comun', 'Poco común'), ('raro', 'Raro'), ('epico', 'Épico'), ('legendario', 'Legendario'), ('mitico', 'Mítico')], max_length=20)),
                ('color', models.CharField(max_length=30)),
                ('logro_requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmeticos', to='gamification.logromodel')),
            ],
            options={
                'db_table': 'gamification_cosmetico',
            },
        ),
        migrations.CreateModel(
            name='XpOtorgadoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estudiante_id', models.UUIDField()),
                ('laboratorio_id', models.UUIDField()),
                ('xp', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gamification_xp_otorgado',
                'indexes': [models.Index(fields=['estudiante_id'], name='idx_xp_estudiante')],
                'constraints': [models.UniqueConstraint(fields=('estudiante_id', 'laboratorio_id'), name='uq_xp_estudiante_laboratorio')],
            },
        ),
        migrations.CreateModel(
            name='CosmeticoDesbloqueadoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estudiante_id', models.UUIDField()),
                ('equipado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cosmetico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desbloqueos', to='gamification.cosmeticomodel')),
            ],
            options={
                'db_table': 'gamification_cosmetico_desbloqueado',
                'indexes': [models.Index(fields=['estudiante_id'], name='idx_cosmetico_desb_estudiante')],
                'constraints': [models.UniqueConstraint(fields=('estudiante_id', 'cosmetico'), name='uq_cosmetico_estudiante')],
            },
        ),
        migrations.CreateModel(
            name='LogroDesbloqueadoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estudiante_id', models.UUIDField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desbloqueos', to='gamification.logromodel')),
            ],
            options={
                'db_table': 'gamification_logro_desbloqueado',
                'constraints': [models.UniqueConstraint(fields=('estudiante_id', 'logro'), name='uq_logro_estudiante')],
            },
        ),
    ]
