# Generated by Django 6.0.7 on 2026-07-31 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiljugadormodel',
            name='avatar_tipo',
            field=models.CharField(choices=[('preset', 'Preset'), ('subido', 'Subido')], default='preset', max_length=10),
        ),
        migrations.AddField(
            model_name='perfiljugadormodel',
            name='avatar_valor',
            field=models.CharField(default='operador_nocturno', max_length=500),
        ),
        migrations.AlterField(
            model_name='cosmeticomodel',
            name='tipo',
            field=models.CharField(choices=[('hoodie', 'Hoodie'), ('gafas', 'Gafas'), ('mascara', 'Máscara'), ('aura', 'Aura'), ('insignia', 'Insignia'), ('mochila', 'Mochila'), ('guantes', 'Guantes'), ('zapatos', 'Zapatos'), ('gorra', 'Gorra'), ('audifonos', 'Audífonos'), ('marco', 'Marco')], max_length=20),
        ),
        migrations.CreateModel(
            name='TituloModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('rareza', models.CharField(choices=[('comun', 'Común'), ('poco_comun', 'Poco común'), ('raro', 'Raro'), ('epico', 'Épico'), ('legendario', 'Legendario'), ('mitico', 'Mítico')], max_length=20)),
                ('logro_requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='gamification.logromodel')),
            ],
            options={
                'db_table': 'gamification_titulo',
            },
        ),
        migrations.CreateModel(
            name='TituloDesbloqueadoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estudiante_id', models.UUIDField()),
                ('equipado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desbloqueos', to='gamification.titulomodel')),
            ],
            options={
                'db_table': 'gamification_titulo_desbloqueado',
                'indexes': [models.Index(fields=['estudiante_id'], name='idx_titulo_desb_estudiante')],
                'constraints': [models.UniqueConstraint(fields=('estudiante_id', 'titulo'), name='uq_titulo_estudiante')],
            },
        ),
    ]
