"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',

    'modules.authentication',
    'modules.users',
    'modules.laboratories',
    'modules.assignments',
    'modules.progress',
    'modules.reports',
    'modules.notifications',
    'modules.audit',
    'modules.lab_environments',
    'modules.roadmap',
    'modules.gamification',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB'),
        'USER': env('POSTGRES_USER'),
        'PASSWORD': env('POSTGRES_PASSWORD'),
        'HOST': env('POSTGRES_HOST', default='localhost'),
        'PORT': env('POSTGRES_PORT', default='5432'),
    }
}


# Redis / Celery
# https://docs.celeryq.dev/en/stable/userguide/configuration.html

REDIS_URL = env('REDIS_URL', default='redis://localhost:6379/0')
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL


# Email
# https://docs.djangoproject.com/en/6.0/topics/email/

EMAIL_BACKEND = env(
    'EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='no-reply@platlab.local')


# Storage (adjuntos de reportes, imágenes de contenido)
# Local en dev; se reemplaza por S3/MinIO en producción vía STORAGES (RNF-08.1)

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# seguridad.md — techo global de memoria por request. El límite real por
# tipo de archivo lo aplican los storage adapters (avatar_storage.py,
# storage_adapter.py, dockerfile_storage.py, el mayor es 5MB), esto es
# un resguardo adicional a nivel de Django: por encima de este tamaño,
# Django corta el parseo del request en vez de bufferizarlo entero.
DATA_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024  # 6 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024  # 6 MB


# OAuth2 (Google / GitHub) — Authorization Code + PKCE (seguridad.md §3)
# client_secret siempre vía variable de entorno, nunca en código fuente.

GOOGLE_OAUTH_CLIENT_ID = env('GOOGLE_OAUTH_CLIENT_ID', default='')
GOOGLE_OAUTH_CLIENT_SECRET = env('GOOGLE_OAUTH_CLIENT_SECRET', default='')
GOOGLE_OAUTH_REDIRECT_URI = env(
    'GOOGLE_OAUTH_REDIRECT_URI', default='http://localhost:5173/oauth/google/callback'
)

GITHUB_OAUTH_CLIENT_ID = env('GITHUB_OAUTH_CLIENT_ID', default='')
GITHUB_OAUTH_CLIENT_SECRET = env('GITHUB_OAUTH_CLIENT_SECRET', default='')
GITHUB_OAUTH_REDIRECT_URI = env(
    'GITHUB_OAUTH_REDIRECT_URI', default='http://localhost:5173/oauth/github/callback'
)


# CORS (django-cors-headers) — el frontend (Vite, puerto 5173 por
# defecto) corre en otro origen que la API; sin esto el navegador
# bloquea las requests aunque curl/Postman funcionen igual.
CORS_ALLOWED_ORIGINS = env.list(
    'CORS_ALLOWED_ORIGINS', default=['http://localhost:5173', 'http://127.0.0.1:5173']
)
CORS_ALLOW_CREDENTIALS = True


# lab_environments — entornos de práctica reales (contenedor Docker por
# estudiante, ver modules/lab_environments). Límites conservadores para un
# único host de desarrollo; ajustables sin tocar código.
LAB_ENV_MAX_CONCURRENTES = env.int('LAB_ENV_MAX_CONCURRENTES', default=5)
LAB_ENV_IDLE_MINUTES = env.int('LAB_ENV_IDLE_MINUTES', default=20)
LAB_ENV_MAX_LIFETIME_MINUTES = env.int('LAB_ENV_MAX_LIFETIME_MINUTES', default=120)


# OpenAlex — verificación académica (ORCID + nombre + publicaciones) al
# solicitar convertirse en instructor (modules/users). API pública, sin
# credenciales; `mailto` es opcional y solo mejora la prioridad en el
# "polite pool" de OpenAlex.
OPENALEX_MAILTO = env('OPENALEX_MAILTO', default='')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.CursorPagination',
    'PAGE_SIZE': 20,
    'EXCEPTION_HANDLER': 'config.exception_handler.custom_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'modules.authentication.infrastructure.authentication.JWTAuthentication',
    ],
    # Protegido por defecto (api.md §1: "JWT Bearer... en todo endpoint
    # salvo los explícitamente públicos"). Cada endpoint público declara
    # permission_classes = [AllowAny] explícitamente, en vez de que lo
    # público sea el default — un olvido nunca deja un endpoint abierto
    # por accidente.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# drf-spectacular (documentación OpenAPI, ver api.md §1)
# https://drf-spectacular.readthedocs.io/en/latest/settings.html

SPECTACULAR_SETTINGS = {
    'TITLE': 'PlatLAB API',
    'DESCRIPTION': 'API REST de PlatLAB — plataforma de laboratorios de ciberseguridad.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# SimpleJWT (ver seguridad.md §2 — tiempos de vida y claims mínimos)
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'USER_ID_CLAIM': 'sub',
}
