# Generated by Django 6.0.7 on 2026-07-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificacionmodel_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionmodel',
            name='tipo',
            field=models.CharField(choices=[('invitacion', 'Invitación'), ('vencimiento_proximo', 'Vencimiento próximo'), ('reporte_resuelto', 'Reporte resuelto'), ('laboratorio_publicado', 'Laboratorio publicado'), ('acceso_vencido', 'Acceso vencido'), ('instructor_aprobado', 'Instructor aprobado'), ('instructor_rechazado', 'Instructor rechazado'), ('laboratorio_aprobado', 'Laboratorio aprobado'), ('laboratorio_rechazado', 'Laboratorio rechazado')], max_length=30),
        ),
    ]
