# Generated by Django 6.0.7 on 2026-07-31 13:20

import django.db.models.constraints
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRoadmapModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roadmap_categoria',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='NodoRoadmapModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('laboratorio_id', models.UUIDField(unique=True)),
                ('posicion', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='roadmap.categoriaroadmapmodel')),
            ],
            options={
                'db_table': 'roadmap_nodo',
                'ordering': ['posicion'],
                'indexes': [models.Index(fields=['categoria', 'posicion'], name='idx_roadmap_nodo_cat_pos')],
                'constraints': [models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('categoria', 'posicion'), name='uq_roadmap_nodo_categoria_posicion')],
            },
        ),
    ]
